### ISSUE TITLE
Help to Config ngPrime

### ISSUE THREAD

**Issue by abnersouzarocket** [spock123/angular2-webpack2-typescript2#2]
Hi,

First your project looks sharp, I clone it. I've been trying for days to make primeng to work on it.

I tried different things:
- setup using: http://www.primefaces.org/primeng/#/setup
1 - Added "primeng": "^1.0.0-beta.13", "primeui": "^4.1.15" to package.json then npm install
2 - import 'primeng/primeng'; in the vendor.ts
3 - Import some primeng modules to the app.module.ts
      import {InputTextModule, ButtonModule } from 'primeng/primeng';
4 - Added it to imports

Then I tried to run, after trying saw some issue with sourcemappings after adding helpers.root('node_modules/primeng') to the exclude part in the preloaders it was gone.

I can see the control, but they are not using anything from primeng, I dont think the controles are being loaded at all, i just see a normal textbox and normal button.

One thing I tried from https://github.com/akveo/ng2-admin/issues/25 I was to copy the theme folder and min.css and min.js from the node_modules also no success.

I download one of the project that they have using webpack (https://github.com/primefaces/primeng-quickstart-webpack) runs ok, but the project is really just a start, webpack need a lot of config. The issue there is having all the .js and map files in the project also, if you look the webpack config is just simple configured.

Really appreciate if you could give a hand on that.

Thanks

**Comment by spock123** [comment]
I'll try to have a look at it later.

I can try to make a clone of my repo using ngPrime instead of Material.

**Comment by spock123** [comment]
Hi againl
- so I'm almost done with fixing the repo, but I'll have to finish the rest tomorrow as I have to go out.

Stay tuned :)

**Comment by spock123** [comment]
@abnersouzarocket  
I've created a branch called ngPrime of my repo.
It now works with ngPrime, with styles and everything.

Short list of what I've modified:

- Removed Material2 modules, components, references in package.json
- Added ngPrime, ngPrimeUI components
- Added a new Angular2 shared module for the ngPrime components
- Added a test-component and a /test route with some ngPrime example components
- Installed Font-awesome
- Added loaders for png, gif, ttf fonts in Font-awesome and ngPrimeUI css
- Load the CSS styling from ngPrime in bootstrap.ts

Hope you can use it - check out the branch and have a look.

Cheers

**Comment by abnersouzarocket** [comment]
@spock123 Thanks a lot for what have you done... That will help so much, notice that most of the places don't show how to properly implement it using webpack with a correct configuration.

I will have a look at it this week and let you know.

Thanks again.
